-- Schema snapshot for db::migrate (issue #308).
-- Generated by running `cargo test schema_snapshot_test -- --nocapture`
-- after a schema change and pasting the output here.
--
-- To regenerate: run the schema_snapshot_test and copy the printed statements.
-- Every statement ends with a lone `;` line as a separator.

CREATE INDEX idx_api_keys_hash ON api_keys(key_hash)
;
CREATE INDEX idx_api_keys_merchant ON api_keys(merchant_id)
;
CREATE INDEX idx_payments_created_id ON payments(created_at DESC, id DESC)
;
CREATE INDEX idx_payments_memo ON payments(memo)
;
CREATE INDEX idx_payments_status ON payments(status)
;
CREATE INDEX idx_payments_status_expires_at ON payments(status, expires_at)
         WHERE status IN ('pending', 'underpaid')
;
CREATE INDEX idx_webhook_deliveries_payment
         ON webhook_deliveries(payment_id)
;
CREATE INDEX idx_webhook_deliveries_redrive
         ON webhook_deliveries(status, attempts, last_attempt, created_at)
         WHERE status IN ('pending', 'failed')
;
CREATE TABLE api_keys (
            id TEXT PRIMARY KEY,
            merchant_id TEXT NOT NULL,
            key_hash TEXT NOT NULL UNIQUE,
            prefix TEXT NOT NULL,
            label TEXT,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
            last_used_at TEXT,
            revoked_at TEXT
        )
;
CREATE TABLE idempotency_keys (
            merchant_id TEXT NOT NULL,
            idempotency_key TEXT NOT NULL,
            payment_id TEXT NOT NULL,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
            PRIMARY KEY (merchant_id, idempotency_key)
        )
;
CREATE TABLE kv_state (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
        )
;
CREATE TABLE merchants (
            id TEXT PRIMARY KEY,
            api_key_hash TEXT UNIQUE,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
        )
;
CREATE TABLE payments (
            id TEXT PRIMARY KEY,
            merchant_id TEXT NOT NULL DEFAULT 'anonymous',
            destination_address TEXT NOT NULL,
            memo TEXT NOT NULL UNIQUE,
            amount TEXT NOT NULL,
            asset TEXT NOT NULL DEFAULT 'XLM',
            asset_issuer TEXT,
            status TEXT NOT NULL DEFAULT 'pending',
            webhook_url TEXT,
            tx_hash TEXT,
            paid_amount TEXT,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
            updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
            expires_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now','+1 hour'))
        )
;
CREATE TABLE processed_transactions (
            payment_id TEXT NOT NULL,
            /* The transaction hash is part of the dedup key, so an empty value
            would make every unhashed record collide and silently discard all
            but the first (issue #224). Reject it in the schema as well as at
            the write path. */
            tx_hash TEXT NOT NULL CHECK (tx_hash <> ''),
            /* Zero-based index of this operation within its transaction.
            Combined with tx_hash to form a unique key per operation so that
            multiple operations in one transaction are each credited
            independently (issues #614, #615). Defaults to 0 for
            single-operation transactions and for rows backfilled from legacy
            data that predate this column. */
            operation_index INTEGER NOT NULL DEFAULT 0,
            amount_stroops INTEGER NOT NULL,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now')),
            PRIMARY KEY (payment_id, tx_hash, operation_index)
        )
;
CREATE TABLE webhook_deliveries (
            id TEXT PRIMARY KEY,
            payment_id TEXT NOT NULL,
            url TEXT NOT NULL,
            payload TEXT NOT NULL,
            event_type TEXT,
            status TEXT NOT NULL DEFAULT 'pending',
            attempts INTEGER NOT NULL DEFAULT 0,
            last_attempt TEXT,
            created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%SZ','now'))
        , acknowledged_at TEXT, manual_attempts INTEGER NOT NULL DEFAULT 0)
;
